### ISSUE TITLE
doesn't install in VS2013

### ISSUE THREAD

**Issue by pagnew** [lennybacon/KarmaVS#1]
12/17/2013 4:12:36 PM - Microsoft VSIX Installer
12/17/2013 4:12:36 PM - -------------------------------------------
12/17/2013 4:12:36 PM - Initializing Install...
12/17/2013 4:12:37 PM - Extension Details...
12/17/2013 4:12:37 PM -     Identifier      : 7ca5e40e-4946-4da8-be1f-b3bab3e8adfc
12/17/2013 4:12:37 PM -     Name            : KarmaVs
12/17/2013 4:12:37 PM -     Author          : devcoach
12/17/2013 4:12:37 PM -     Version         : 1.0
12/17/2013 4:12:37 PM -     Description     : Use Karma for Continous JavaScript Testing with feedback through the Visual Studio Output Window
12/17/2013 4:12:37 PM -     Locale          : en-US
12/17/2013 4:12:37 PM -     MoreInfoURL     : 
12/17/2013 4:12:37 PM -     InstalledByMSI  : False
12/17/2013 4:12:37 PM -     SupportedFrameworkVersionRange : [4.5]
12/17/2013 4:12:37 PM - 
12/17/2013 4:12:37 PM -     Supported Products : 
12/17/2013 4:12:37 PM -         Microsoft.VisualStudio.Pro
12/17/2013 4:12:37 PM -             Version : [11.0]
12/17/2013 4:12:37 PM - 
12/17/2013 4:12:37 PM -     References      : 
12/17/2013 4:12:37 PM -         -------------------------------------------------------
12/17/2013 4:12:37 PM -         Identifier   : Microsoft.VisualStudio.MPF.11.0
12/17/2013 4:12:37 PM -         Name         : Visual Studio MPF 11.0
12/17/2013 4:12:37 PM -         Version      : [11.0]
12/17/2013 4:12:37 PM -         MoreInfoURL  : 
12/17/2013 4:12:37 PM -         Nested       : No
12/17/2013 4:12:37 PM - 
12/17/2013 4:12:37 PM - 
12/17/2013 4:12:37 PM - Searching for applicable products...
12/17/2013 4:12:37 PM - Found installed product - Microsoft Visual Studio Professional 2013
12/17/2013 4:12:37 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
12/17/2013 4:12:37 PM - Found installed product - Global Location
12/17/2013 4:12:37 PM - Found installed product - ssms
12/17/2013 4:12:37 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by lennybacon** [comment]
Added VS2013 Support
