### ISSUE TITLE
Build as extension for Visual Studio 2015

### ISSUE THREAD

**Issue by ChrisBellew** [lennybacon/KarmaVS#12]
Any idea what this would involve, just building with the VS2015 SDK?

**Comment by lennybacon** [comment]
Adding version 13.0 (for vs2015) to src/KarmaVs/source.extension.vsixmanifest should be it. Would you like to open a PR?

**Comment by ChrisBellew** [comment]
Sure. Will do. Can I help with submitting it to the extensions repo as well
or can only you do that?

Thanks,
Chris

**Comment by lennybacon** [comment]
That's my job. Will do after PR. Thanks!
