### ISSUE TITLE
Web project not found if in Virtual folder

### ISSUE THREAD

**Issue by georgeono** [lennybacon/KarmaVS#2]
If you have a virtual folder in the solution, then the Karma output indicates that no web project was found:
INFO: No web project found with a file named "karma.unit.conf.js" in the root directory.

My situation:
Solution: Frontend.sln
Virtual folder: Tests (created using the option: Add > New Solution Folder)
Web project: Web.Tests

Tests/
  Web.Tests

If I move the Web.Tests project outside the virtual folder, then the Karma output indicates that the project was found.

**Comment by lennybacon** [comment]
Just added support for that.
