### ISSUE TITLE
Does not look for standard karma.conf.js file

### ISSUE THREAD

**Issue by JamieDixon** [lennybacon/KarmaVS#4]
In order for this plugin to work it seems to look for karma.unit.conf.js instead of the standard karma.conf.js.

If you want both command line and VS integration support at present, you need to maintain two copies of the same data in these files.

**Comment by lennybacon** [comment]
As the documentation says (http://karma-runner.github.io/0.10/intro/configuration.html) you CAN start karma passing a config file to use:

e.g.:
    $ karma init my.conf.js

As there are two different scenarios (e2e and unit test) from my perspective it absolutely makes sense to have two configs as they point to different tests.

**Comment by JamieDixon** [comment]
That's a fair point. Passing the location of the config is pretty simple so that solves the main issue. I'm curious to know what you mean by two different scenarios. Which tests are e2e vs unit in the case of the plugin? Is it that you use the plugin to run a different suite of tests than you usually would in the command line runner?

**Comment by lennybacon** [comment]
e2e: http://docs.angularjs.org/guide/dev_guide.e2e-testing

Where you can remote control browser navigation and user interaction aka integration test.

unit test: e.g.: https://github.com/pivotal/jasmine

Where you try to test the smallest possible unit without (ideally) any dependencies (at least no db/no network/ no file system/ no date/ ...)
