### ISSUE TITLE
Non standard installation : ERROR: Karma was not found

### ISSUE THREAD

**Issue by garycuthbert** [lennybacon/KarmaVS#9]
Hello, great plugin, it has been very useful but i have run into a problem...

Because of path issue on our automated build environment i need to change the node npm global install location to something other than %appdata% which is user specific. 

I was able to achieve this with the npm config set prefix command e.g.
npm config set prefix c:\global_npm_modules
And now when i install the karma + dependent packages via npm they do indeed install to  'c:\global_npm_modules\node_modules'

I can successfully run karma from a command line in this environment (i.e. 'karma start karma.unit.conf.js') however the KarmaVS plugin gives the following output:

INFO: Node installation found: C:\Program Files\nodejs\node.exe
ERROR: Karma was not found. Run "npm install -g karma"...

Do you know what mechanism is used to locate Karma? i have tried adding 'c:\global_npm_modules' to the system path variable but i still get the above error.

Many thanks

**Comment by garycuthbert** [comment]
Hello, i have had a look at the code an can see the karma path is constructed from 'Environment.SpecialFolder.ApplicationData'. I appreciate this matches the default installation path npm uses however as i mentioned above I need to use a more generic path than the user centric %appdata% one that windows 7 sets.

Would there be any scope to change this to access the karma location based on the npm prefix value? not sure how easy that would be...

**Comment by lennybacon** [comment]
You could make a pull request that takes a different location e.g. from a config file with the fall back to the current location.
